version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 54322:${DB_PORT}
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: --requirepass ${REDIS_PASSWORD}
