FROM node:17.8 as base

WORKDIR /app
COPY package.json .
COPY package-lock.json package-lock.json

RUN npm ci
COPY . .

# Test
FROM base as test
RUN npm run test

# BUILD
FROM base as build
RUN npm run prebuild && npm run build

# RUNTIME IMAGE
FROM node:17.8 as production

WORKDIR /app
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/dist /app/dist
EXPOSE 3000

CMD ["node", "dist/main.js"]