apiVersion: apps/v1
kind: Deployment
metadata:
  name: forumdb
spec:
  selector:
    matchLabels:
      app: forumdb
  template:
    metadata:
      labels:
        app: forumdb
    spec:
      containers:
        - name: forumdb
          image: postgres:15.1
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              value: production
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_PASS
                  optional: false
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: dbdata
      volumes:
        - name: dbdata
          hostPath:
            path: /home/dbdata
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: forumdb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: forumdb