apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.6.0
          env:
            - name: SERVER_PORT
              value: "5601"
            - name: SERVER_NAME
              value: kibana
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 5601

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601